#!/bin/bash

set -e
set -u

SRC=$1
DEST=$2
DPI=$3

echo "... $SRC/*.svg ==> $DEST/*.png"

find $SRC -name "*.svg" -print | \
while read F; do
{
    NAME=${F##*/}
    NAME=${NAME%.svg}

    SVG="$SRC/$NAME.svg"
    PNG="$DEST/$NAME.png"

    if [[ "$SVG" -nt "$PNG" ]]; then
        echo "$SVG --export-png=$PNG --export-dpi=$3"
        echo "... $SVG --export-png=$PNG --export-dpi=$3" >&2
    fi
}; done | \
    inkscape --shell
