#!/bin/bash

set -e
set -u

SRC=$1
DEST=$2
DPI=$3

mkdir -p "$DEST"

function ink()
{
    find $SRC -name "*.svg" -print | \
    while read F; do
    {
        NAME=${F##*/}
        NAME=${NAME%.svg}

        SVG="$SRC/$NAME.svg"
        PNG="$DEST/$NAME.png"

        if [[ "$SVG" -nt "$PNG" ]]; then
            inkscape \
                --export-type=png \
                --export-filename=$PNG \
                --export-dpi=$DPI \
                $SVG
            echo ".. svg->png $PNG" 1>&2
        fi
    }; done
}

ink 2>&1
