#!/bin/bash

set -u
set -e

echo ".. Changing all levels to standard format"
for L in \
    $(find \
        rabbit-escape-engine/src/rabbitescape/levels \
        -name "test" -prune -o \
        -name "development" -prune -o \
        -name "staging" -prune -o \
        -name "gifs" -prune -o \
        -name "*.rel" -print \
    ); do
{
    echo "..." $L
    ./runrabbit --placeholders $L
}; done
